server:
  port: 2333
  address: 0.0.0.0

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    remoteCipher:
      url: "http://virusmusicbot_yt_cipher:8001"
    oauth:
      enabled: true
      skipInitialization: true
      refreshToken: "${YOUTUBE_REFRESH_TOKEN:}"
    clients:
      - TV
      - WEB
      - ANDROID_VR
      - ANDROID_MUSIC
    clientOptions:
      TV:
        playback: true
        playlistLoading: false
        searching: false
        videoLoading: true
      WEB:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      ANDROID_VR:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
      ANDROID_MUSIC:
        playback: true
        playlistLoading: true
        searching: true
        videoLoading: true
  lavasrc:
    providers:
      - 'ytsearch:"%ISRC%"'
      - 'ytsearch:%QUERY%'
    sources:
      spotify: true
      appleMusic: false
      deezer: false
      yandexMusic: false
      flowerytts: false
      youtube: false
    spotify:
      clientId: ${SPOTIFY_CLIENT_ID}
      clientSecret: ${SPOTIFY_CLIENT_SECRET}
      spDc: ${SPOTIFY_SPDC}
      countryCode: US
      playlistLoadLimit: 6
      albumLoadLimit: 6
      resolveArtistsInSearch: true
      localFiles: false

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.2"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.3"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: ${LAVALINK_PASSWORD}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 6
    resamplingQuality: LOW
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    filters:
      volume: true
      equalizer: true
      karaoke: false
      timescale: false
      tremolo: false
      vibrato: false
      distortion: false
      rotation: false
      channelMix: false
      lowPass: false
    nonAllocating: false

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: DEBUG
    dev.lavalink.youtube: DEBUG
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: DEBUG
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
